import { z } from 'zod';
export declare const ProductCategorySchema: z.ZodEnum<["cleanser", "toner", "essence", "serum", "ampoule", "moisturizer", "sunscreen", "treatment", "oil", "mask", "eye_cream"]>;
export declare const RoutineStepCategorySchema: z.ZodEnum<["cleanse", "tone", "treat", "hydrate_moisturize", "protect_spf"]>;
export declare const ActiveCategorySchema: z.ZodEnum<["retinoid", "aha", "bha", "pha", "vitamin_c_l_ascorbic", "vitamin_c_derivative", "niacinamide", "benzoyl_peroxide", "azelaic_acid", "centella_cica", "ceramides", "hyaluronic_acid", "snail_mucin", "peptides", "panthenol"]>;
export declare const FragranceStatusSchema: z.ZodEnum<["fragrance_free", "contains_fragrance", "unknown"]>;
export declare const AmPmCompatibilitySchema: z.ZodEnum<["AM_ONLY", "PM_ONLY", "AM_AND_PM"]>;
export declare const ProductSchema: z.ZodObject<{
    productId: z.ZodString;
    brand: z.ZodString;
    name: z.ZodString;
    category: z.ZodEnum<["cleanser", "toner", "essence", "serum", "ampoule", "moisturizer", "sunscreen", "treatment", "oil", "mask", "eye_cream"]>;
    routineStep: z.ZodEnum<["cleanse", "tone", "treat", "hydrate_moisturize", "protect_spf"]>;
    variant: z.ZodOptional<z.ZodString>;
    size: z.ZodOptional<z.ZodString>;
    barcode: z.ZodOptional<z.ZodString>;
    inciIngredients: z.ZodArray<z.ZodString, "many">;
    keyIngredients: z.ZodArray<z.ZodString, "many">;
    activeCategories: z.ZodArray<z.ZodEnum<["retinoid", "aha", "bha", "pha", "vitamin_c_l_ascorbic", "vitamin_c_derivative", "niacinamide", "benzoyl_peroxide", "azelaic_acid", "centella_cica", "ceramides", "hyaluronic_acid", "snail_mucin", "peptides", "panthenol"]>, "many">;
    fragranceStatus: z.ZodEnum<["fragrance_free", "contains_fragrance", "unknown"]>;
    productDirections: z.ZodString;
    manufacturerWarnings: z.ZodOptional<z.ZodString>;
    amPmCompatibility: z.ZodEnum<["AM_ONLY", "PM_ONLY", "AM_AND_PM"]>;
    safetyReviewStatus: z.ZodEnum<["approved", "pending", "rejected"]>;
    catalogStatus: z.ZodEnum<["active", "disabled"]>;
    ingredientSource: z.ZodEnum<["manufacturer", "licensed_catalog", "user_submitted_unverified"]>;
    ingredientSourceConfidence: z.ZodNumber;
    countryAvailability: z.ZodArray<z.ZodString, "many">;
    averagePriceUsd: z.ZodOptional<z.ZodNumber>;
    imageUrl: z.ZodOptional<z.ZodString>;
    createdAt: z.ZodString;
    lastVerifiedAt: z.ZodString;
}, "strip", z.ZodTypeAny, {
    productId: string;
    brand: string;
    name: string;
    category: "cleanser" | "toner" | "essence" | "serum" | "ampoule" | "moisturizer" | "sunscreen" | "treatment" | "oil" | "mask" | "eye_cream";
    routineStep: "cleanse" | "tone" | "treat" | "hydrate_moisturize" | "protect_spf";
    activeCategories: ("retinoid" | "aha" | "bha" | "pha" | "vitamin_c_l_ascorbic" | "vitamin_c_derivative" | "niacinamide" | "benzoyl_peroxide" | "azelaic_acid" | "centella_cica" | "ceramides" | "hyaluronic_acid" | "snail_mucin" | "peptides" | "panthenol")[];
    fragranceStatus: "fragrance_free" | "contains_fragrance" | "unknown";
    inciIngredients: string[];
    keyIngredients: string[];
    productDirections: string;
    amPmCompatibility: "AM_ONLY" | "PM_ONLY" | "AM_AND_PM";
    safetyReviewStatus: "approved" | "pending" | "rejected";
    catalogStatus: "active" | "disabled";
    ingredientSource: "manufacturer" | "licensed_catalog" | "user_submitted_unverified";
    ingredientSourceConfidence: number;
    countryAvailability: string[];
    createdAt: string;
    lastVerifiedAt: string;
    variant?: string | undefined;
    size?: string | undefined;
    barcode?: string | undefined;
    manufacturerWarnings?: string | undefined;
    averagePriceUsd?: number | undefined;
    imageUrl?: string | undefined;
}, {
    productId: string;
    brand: string;
    name: string;
    category: "cleanser" | "toner" | "essence" | "serum" | "ampoule" | "moisturizer" | "sunscreen" | "treatment" | "oil" | "mask" | "eye_cream";
    routineStep: "cleanse" | "tone" | "treat" | "hydrate_moisturize" | "protect_spf";
    activeCategories: ("retinoid" | "aha" | "bha" | "pha" | "vitamin_c_l_ascorbic" | "vitamin_c_derivative" | "niacinamide" | "benzoyl_peroxide" | "azelaic_acid" | "centella_cica" | "ceramides" | "hyaluronic_acid" | "snail_mucin" | "peptides" | "panthenol")[];
    fragranceStatus: "fragrance_free" | "contains_fragrance" | "unknown";
    inciIngredients: string[];
    keyIngredients: string[];
    productDirections: string;
    amPmCompatibility: "AM_ONLY" | "PM_ONLY" | "AM_AND_PM";
    safetyReviewStatus: "approved" | "pending" | "rejected";
    catalogStatus: "active" | "disabled";
    ingredientSource: "manufacturer" | "licensed_catalog" | "user_submitted_unverified";
    ingredientSourceConfidence: number;
    countryAvailability: string[];
    createdAt: string;
    lastVerifiedAt: string;
    variant?: string | undefined;
    size?: string | undefined;
    barcode?: string | undefined;
    manufacturerWarnings?: string | undefined;
    averagePriceUsd?: number | undefined;
    imageUrl?: string | undefined;
}>;
export declare const MerchantNameSchema: z.ZodEnum<["iherb", "yesstyle", "sephora", "ulta", "amazon", "brand_direct", "other"]>;
export declare const ProductOfferSchema: z.ZodObject<{
    offerId: z.ZodString;
    productId: z.ZodString;
    merchant: z.ZodEnum<["iherb", "yesstyle", "sephora", "ulta", "amazon", "brand_direct", "other"]>;
    merchantDisplayName: z.ZodString;
    region: z.ZodString;
    price: z.ZodNumber;
    currency: z.ZodString;
    inStock: z.ZodBoolean;
    shippingAvailability: z.ZodArray<z.ZodString, "many">;
    affiliateUrl: z.ZodString;
    affiliateProvider: z.ZodEnum<["sovrn", "impact", "partnerize", "direct", "awin"]>;
    commissionRatePercent: z.ZodNumber;
    lastVerifiedAt: z.ZodString;
    deepLinkUrl: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    productId: string;
    lastVerifiedAt: string;
    offerId: string;
    merchant: "iherb" | "yesstyle" | "sephora" | "ulta" | "amazon" | "brand_direct" | "other";
    merchantDisplayName: string;
    region: string;
    price: number;
    currency: string;
    inStock: boolean;
    shippingAvailability: string[];
    affiliateUrl: string;
    affiliateProvider: "sovrn" | "impact" | "partnerize" | "direct" | "awin";
    commissionRatePercent: number;
    deepLinkUrl?: string | undefined;
}, {
    productId: string;
    lastVerifiedAt: string;
    offerId: string;
    merchant: "iherb" | "yesstyle" | "sephora" | "ulta" | "amazon" | "brand_direct" | "other";
    merchantDisplayName: string;
    region: string;
    price: number;
    currency: string;
    inStock: boolean;
    shippingAvailability: string[];
    affiliateUrl: string;
    affiliateProvider: "sovrn" | "impact" | "partnerize" | "direct" | "awin";
    commissionRatePercent: number;
    deepLinkUrl?: string | undefined;
}>;
//# sourceMappingURL=product.schema.d.ts.map